### ISSUE TITLE
Boot picker OC & installation with Clover or OC?

### ISSUE THREAD

**Issue by DeMikeyyy** [lersy/Dell-7577-Hackintosh-macos-Opencore#1]
Let me start by saying there isn't really an issue and my Hackintosh runs perfectly thanks to you. I created a Github account just for this! :D 

However just a couple of questions:

- Why can't I enable bootpicker in OC? If I do, a password is asked. In the earlier release, it did work but very very laggy 
- I tried installing MacOS with this OC config but it was quite clear that it wouldn't ever work. Do you recommend Clover for installing and once it's installed swapping EFI to Clover? Or did you make another config of OC for installing? Does installing with Clover and then switching to OC after that have any effect on the OS as it was installed by Clover and maybe MacOS will trip over that?

I also have the 7300HQ model instead of 7700HQ, so will the SMBIOS have effect on that? Other guides (Clover) choose MacBookPro14,1 for 7300HQ.

Thanks again for making the switch to OC possible, laptops can be hard. I got as far as booting the system by myself, but USB/sleep and such weren't working.

**Comment by lersy** [comment]
Hey mate. I am glad it helps you. Thanks for creating an account :D 

I try to explain your questions and some other work arounds as much as I can.

* I don't know about that password stage. I can enable picker with no problems and passwords. I am not using FileVault or other things. Tonight I will upload my current EFI folder, give another try with it and please write your situation again.

* I just installed macOS again yesterday with OC. I made some modifications on config.plist of course. There are things to consider. I will upload a more general EFI folder and make detailed explanations regarding to that. But here are things before hand.

I nearly changed nothing much but there is an issue with VoodooI2C so touchpad does not work on installation and after os upgrade. The thing is VoodooI2C relies on a native kext but on installation and after updates you have to make kextcache to work it. Since I have a usb mouse, I do not care about it that much. I just plug my usb mouse on installation and after upgrades, make a kextcache and reboot. ho la la! everything is ok again. this is not an issue with OC but that kext. Developers talked among themselves and it seems VoodooI2c team is not volunteer to change it. In Clover, there is a section "Forcekextstoload". I suppose you can achieve this issue with that thing but there is no such option in OC. If you do not have a usb mouse to use, then I recommend you to use ApplePS2smarttouchpad.kext for installation for both keyboard and mouse. Then you can revert it to voodoops2controller & voodooI2C combination.

About SMBIOS, in general they say two things to consider when choose it. First, it should be closest to your cpu, (e.g Macbook14,3 uses 7700HQ and so does my laptop) This is the reason why I chose it in the first place because it is a perfect match as you can see. The second thing to consider is that they say the smbios you choose should not be shipped with a egpu. (e.g Macbook14,1 was not shipped with an external gpu. it uses only internal gpu. ) I already built my config and have no problem with Apple services including iMessage and FaceTime so I do not want to change it. If I were you, I would stick to 14,3. "HQ" means it has 4 cores and your cpu has also 4 cores. it is closest to 14,3 for that series I believe. Some people say they have better performance with different smbios models. If you have time, you can change them to find best one for you.

SMBIOS is tied to USBPorts.kext. Since I use Macbook14,3, if you just dig into kext and open config.plist of it, you will see sections which say ( Macbook14,3 ). If you want to change your smbios, you should also change it in USBPorts.kext so you can access to your USB ports. I will upload an EFI file which will contain USB-Inject-All and regarding OC quirks for it so one can easily map their own usb kext or ssdt. If you can use all of your USB ports with my kext, you can easily change it inside of kext config file as explained before. What I recommend is mapping your own one is much more suitable for you. And if you want to change smbios to much, it is better to stick with USB-inject-all and SSDT otherwise you have to change each time in kext config. 

I do not have any other ideas right now. Let me discover my efi folder again. Then I will upload it. 

If there are unclear things in your mind, feel free to ask anytime.

**Comment by DeMikeyyy** [comment]
Hey man, thanks for the post. I haven't gotten around installing or changing the MacOS install as my Dell screen is having dead pixels, possibly of carrying it around with other stuff in my backpack?

However, I'll be replacing the screen with a compatible MSI display which has 120hz and will perhaps be brighter then the 7577's display. However, is 120hz supported by default on a Hackintosh so I can keep using your repo?

Once again thanks for all this, it may go unnoticed but installing MacOS on 7577 with OpenCore would be impossible all by myself, using this is a breeze. I can only hope OC/macOS won't fiddle to much with kexts in the future so I can keep using this. 

When I get the working display, I'll be posting an answer to your detailed post, thanks bro. Greeting from Belgium and stay safe!
