### ISSUE TITLE
I made my first Hackintosh and everything works as far as I know

### ISSUE THREAD

**Issue by DeMikeyyy** [lersy/Dell-7577-Hackintosh-macos-Opencore#11]
Hey man!

Guess what? I followed the OC laptop guide on Dortania and got a fully functioning EFI folder based on 0.6.0 Opencore. Here's the link: 

https://drive.google.com/drive/folders/12dBqRP96uVHUGyir7BWVKlBAUznmbJ4_?usp=sharing

I have less SSDT's then you (only PNLF, DGPU OFF, SSDT-USBX and SSDT-PLUG. The touchpad ssdt (TPXX) and brightness keys SSDT I copied from you as I didn't find them. 

The SSDT's I don't use are ALS0, DMAC, MEM2, MCHC, and SBUS. What are you using these for? As far as I know, the laptop works fine without these

However, I will keep using your config because I think you have more knowledge about the patches then me. I'm just trying to learn so in the future if you ever won't update, I can update it myself or help you with issues :)

Also interesting to note that USB ports work fine without the USBPorts kext

Cheers!

**Comment by dbookuz** [comment]
Updated mine also to 0.6.0, everything works as of now i think.. only the wifi i need a terminal auto loader every reboot for it to work. Also as previously stated on ur last topic, the sound on my external monitor is not working, it plays a video but the sound is coming on my laptop.

Does the google drive above is ur efi folder? I requested an access to it, just want to see the difference on mine. Thank you sir! I plan to use this laptop for the next 1-2 years so I may need to educate myself more on OC if ever you both won't update ur laptops :)

**Comment by lersy** [comment]
hey guys 

it is nice for both of you to find your own ways. I am glad to hear this news. What I did was actually reading Opencore own documentation about configuration. When I succeed to boot into macOS then I started searching for more convenient ways to use it. Touchpad and brightness keys part were most problematic ones for me. Then with trial and error I made my own versions of ssdts with less rename patches. 

The ones you asked are about nothing vital but mostly cosmetic. Among them, I suggest you to use ALS0. it makes a fake light sensor so for example when you unplugged your laptop from AC , it dims screen light. of course you need none of these as I said they are cosmetic. SBUS add a device so when you go to system profiler you can see sbus driver is installed under PCI parts section. is it something you need? not at all. 

I have been using O.C 0.6.0 for a time and no issues so far. I update my OC and kexts from time to time with latest commits from their GitHub pages. I read the changes first then I adjust my config and give a go. I suggest you to use a usb stick to boot in these kind of situations if you are not comfortable with your config. 

We all know different things related to our hacktops. I learn from you , you learn from me. I consider three of us as a community. We can combine our knowledge to get a problem free, fast and fully functional ( as much as possible ) macOS environment. 

It is interesting to hear about usbports kext situation. can you handle all usb 2 and usb 3 connections without that kext and any further patches? I will give it a go sometime. Less is better in a way. 

For a time , I am trying quirk RebuiltAppleMemoryMap instead of Enablewriteunprotector. it works without a problem so far and it is suggested to use it if possible. Next time I will enable this quirk by default. You can give it a go now if you want.

if you use discord, we can make a group to talk there. mine is lersy#8888

**Comment by dbookuz** [comment]
I have added you on discord sir @lersy, I think I will be the one who is gonna learn from u guys hahah I'm still a newbie in opencore and doesn't have much time right now trying to understand all of it..
