### ISSUE TITLE
Windows folder in OC / 144hz

### ISSUE THREAD

**Issue by dbookuz** [lersy/Dell-7577-Hackintosh-macos-Opencore#13]
Good day sir, I tried to install windows on my hdd to try dual booting. After I installed windows, I did go back to my ssd (macos) and noticed my EFI folder has windows folder on it. Is it the same on yours since you mentioned that you are also dual booting? Will it affect my efi folder when updating OC folder etc?

Lastly, have you tried to connect this to an external monitor with a 144hz? Thank you sir!

**Comment by lersy** [comment]
Even though I replied this question to you, for further references I leave it here. 

EFI folders are places to make OSes bootable by UEFI BIOS. Here is a scenario to explain things much easier.

Assuming that there are two separate hard drives on a pc and call them DRIVE-0 and DRIVE-1

DRIVE-0 has 100 GB and DRIVE-1 has 200 GB

to use UEFI bootable folder on a drive, we should format it as GPT/GUID Schema. 

let's say we want to install Macos first to our PC. when we format DRIVE-0 on macOS installer with GUID schema , it creates two partition for us automatically. an EFI partition > 200 MB and an APFS partition > Rest of the space. 

We copy Opencore EFI folder on that partition. 

Then we want to install windows. If we do not have an existing EFI partition on one of our drives , windows installer creates one for us automatically on DRIVE-1. but as we have an EFI partition on DRIVE-0, windows installer says no need to create another for boot process , and copy itself on DRIVE-0 EFI partition. 

This is your case as well as mine. It is nothing to worry about except for if you mess up with your DRIVE-0 and its EFI partition you can't boot into windows as well since there is no windows boot manager on either of them. 

I always recommend to have separate EFI partition on both drives. better to install windows first then macOS. but in case you have to reinstall windows , you can adjust these table by yourself with diskpart commands ( another topic, so you should google how to manually format a drive for windows installation )

In terms of second screen, I do not have a second screen now. when I was at my parent's home, there was a samsung tv and I connected my laptop to that on WINDOWS 10. 

DeMikeyyy is the master of second screen you should ask him

**Comment by DeMikeyyy** [comment]
> Good day sir, I tried to install windows on my hdd to try dual booting. After I installed windows, I did go back to my ssd (macos) and noticed my EFI folder has windows folder on it. Is it the same on yours since you mentioned that you are also dual booting? Will it affect my efi folder when updating OC folder etc?
> 
> Lastly, have you tried to connect this to an external monitor with a 144hz? Thank you sir!

I don't have a 144hz monitor but it should be working just fine. Whatevergreen takes care of this I think so just use latest kexts.
