### ISSUE TITLE
No boot options

### ISSUE THREAD

**Issue by ISmokeAir** [lersy/Dell-7577-Hackintosh-macos-Opencore#14]
I have used the last efi folder that was made for opencore 0.6. When I boot to my USB drive it shows just "reset nvram". Any ideas?

**Comment by lersy** [comment]
Can you provide more info please? which macOS version , what kind of formation you used? 

it is set to see apfs volumes only. 

for a workaround you can change value in Misc > Security > ScanPolicy to 0 ( zero )

**Comment by ISmokeAir** [comment]
> Can you provide more info please? which macOS version , what kind of formation you used?
> 
> it is set to see apfs volumes only.
> 
> for a workaround you can change value in Misc > Security > ScanPolicy to 0 ( zero )


I used gibMacOS to make my installer. I am going to try to ser the Scan Policy to 0

**Comment by ISmokeAir** [comment]
Ok, update. I changed the Scan Policy to 0 and it didn't work. I got an error that was documented in the opencore guide that didn't have a solution. I tried your 5.9 release and it went well till it crashed(it think, because onetime it went a little bit further). So, I want to try something else. Can you share on Google drive/Dropbox your efi folder that you are using right now, of course without the serial number and the others.

**Comment by ISmokeAir** [comment]
Maybe the folder on github got corrupted or something. Also can you tell me how did you made your USB drive? You used macos in a vm/real Mac, you used Linux/windows  and the gib macos tool and just put you efi in the efi partition? Also what version of Macos do you have?

**Comment by lersy** [comment]
Hey buddy. Sorry for late reply. I have been away from my pc for a time. 

I used createinstallmethod on a Mac. It is possible to make it on a working hackintosh, too. I do not know about gibmacos process. 

My current macOS is 10.15.6 with all possible supplemental updates. 

I do not think it is broken because I use it to check out after I upload. But I can send you my current efi folder. It is a little bit different from the uploaded one because I tend to use Opencore boot loader with latest commits possible. I config my system with new additions then it releases officially I try it for a couple of days then release. 

You can keep touch with me on discord. I would like to help if I can. It is lersy #8888
