### ISSUE TITLE
Audio and Mic 

### ISSUE THREAD

**Issue by alifayed266** [lersy/Dell-7577-Hackintosh-macos-Opencore#16]
thank you for efi folder but no audio and mic and i try many layout id not do any thing

**Comment by lersy** [comment]
Hey there, 

What is your laptop model? Which components does it have? ( CPU, Audio codec etc. ) Which layouts have you tried so far? How do you try new layouts? 

I suggest you to provide more information before asking question in open source communities and communities like hackintosh. 

In my config, related part is in device properties. When you expand them, you can see built-in audio comment in the related one. It is not in id format. You should change value from dec to hex. 

In order to try out new layouts, I recommend you to remove that part and use boot argument "alcid" when you find the right one, you can convert it then enter the value in to config device properties part. 

My codec correspond id is 21. It is best for my hardware for now, there is no problem with jack or sleep. 

So try layout ids with boot arguments first e.g alcid=21

**Comment by alifayed266** [comment]
Thanks for your reply ..
My laptop is 7577 with 1050ti and i get the audio alc256 work with alcid 13 the speaker ok but headphone not working i tried to change the alcid id but it wont to be changed from 13 to 21 from config.plist

I am using plist editor pro to edit the config file in efi parttion and i save my alc edit and restart nothing changed

Any solution ?

**Comment by lersy** [comment]
Can you upload your config.plist so I can check faster

**Comment by alifayed266** [comment]
Sure
https://drive.google.com/file/d/1P4foAN4RaQ54LMpXh7da5WdOP8NBUmwc/view?usp=drivesdk

**Comment by alifayed266** [comment]
The airdrop not working too but bluetooth work fine i can connect my iphone but just connect

**Comment by lersy** [comment]
[config.plist.zip](https://github.com/lersy/Dell-7577-Hackintosh-macos-Opencore/files/5351539/config.plist.zip)

give this config for your audio related problems.

you have two sections in your config.plist for audio. one of them is in the device properties section, other one is in the NVRAM> boot arguments section. What I did is that I removed the part in device properties and left alcid=21 in the boot arguments part. This is the id I have been using for a long time without having problems with mic and jack.

For airdrop and other stuff related to wifi and bluetooth, they are in the early stage of development so it is a known bug that air drop does not work. But you can use continuity features like having a call , copy and paste from Mac to iPhone or vice versa  , see open applications in the dock or iOS home screen. At least I have these features I can say but as I said it is in the alpha stage now so features are not there fully but team behind it progress well I can say.

**Comment by alifayed266** [comment]
Nothing happend the id still 13 in hackintool and ioservice at the first i tryed to put it 13 but i cant too i put vodohda and delete it and put applealc to get it work randomly

What can i do to let the system read the config file as 21 id ?

**Comment by alifayed266** [comment]
But mic and audio fine the headphone not working

**Comment by lersy** [comment]
Dude, applealc works with vanilla applehda. If you tey voodoohda, it is best to refer to apple alc read me

**Comment by alifayed266** [comment]
I fix it finally
