### ISSUE TITLE
Monterey

### ISSUE THREAD

**Issue by DeMikeyyy** [lersy/Dell-7577-Hackintosh-macos-Opencore#25]
Hey mate, how it's going? Are you still using MacOS? Did you give Monterey a shot? Cheers

**Comment by symabbas** [comment]
Hey!

> Are you still using MacOS?
Yes
> Did you give Monterey a shot?
Yes, the early public release versions, but reverted back to Big Sur because of issues. Will try it out when the final stable version releases next month. 

PS. I am using Mac OS on the Dell 5577. I just visited this repo months ago when I needed some help with the HDMI. Cheers.

**Comment by symabbas** [comment]
Hey!

> Are you still using MacOS? 

> 

Yes!

**Comment by DeMikeyyy** [comment]
> Hey!
> 
> > Are you still using MacOS?
> 
> > 
> 
> Yes!
> 
> > Did you give Monterey a shot?
> 
> > 
> 
> Yes, the early Public Beta Versions, but reverted back to Big Sur to be safe. There was nothing that didn't work on Monterey which already did on Big Sur, but it was the public beta after all. Will try the final release coming next month for sure.
> 
> > 
> 
> PS. I use Mac OS on a Dell 5577. Visited this repo months ago when I needed help with HDMI. Cheers.

Hey man, thanks a lot!! Did the Big Sur efi work from Lersy on your 5577 without any changes?

What changes did you have to make to boot Big Sur? Are you interested in sharing your EFI? Thanks for the spontaneous answer!

**Comment by lersy** [comment]
Hey guys long time no see but I am fine and back :) I am still using Macos on my Dell 7577 with Big Sur. I have never tried Monterey but when it is released I think it will be safe to install it. To be honest, I have never done any change or upgrade to SSDT files just updating Opencore and kexts. 

Have a good day you all

**Comment by DeMikeyyy** [comment]
> Hey guys long time no see but I am fine and back :) I am still using Macos on my Dell 7577 with Big Sur. I have never tried Monterey but when it is released I think it will be safe to install it. To be honest, I have never done any change or upgrade to SSDT files just updating Opencore and kexts.
> 
> Have a good day you all

Hey man thanks and nice to see you still around. I tried beta 7 and updated only OC and kexts but it doesn't boot. Still happy with working Big Sur tho. Cheers

**Comment by DeMikeyyy** [comment]
Hey mate, one more question: what's the deal in Hackintosh community against shared EFI''s like yours? I get it's because ''people don't know what they're doing'', but what's the deal about ''even if your laptop is the same exact hardware, it isn't guaranteed to work''

Do you mean, if I would make my own EFI from scratch, would my laptop would run better, even if the hardware is identical?

Of course I already tried to make my own EFI, but when I compare mine to yours there's so much missing I wouldn't even find some kexts/ssdt's that you found for Dell even if my life depended on it lol. 

I just don't understand why there's such toxic behaviour about sharing EFI as my laptop would never run macOS fully working without you, and along the way I also picked up a lot of knowledge of OC, sorry for the random post lol I couldn't sleep and just thought I would ask your opinion on that and put my thought on paper haha

**Comment by lersy** [comment]
Hi mate how you doin'?

Even though I noticed your question right away, I intently want to answer late because I think this is the most important answer for your question.

As you see, when you depend on someone you also tie your urgency to that other party. One day, if I want to stop updating EFIs or answers, you will be in dark so it is good to know at least basics about what you are doing. 

For other reasons why community against pre-built EFIs:

* there are so many repositories which contain wrong kexts or tweaks or optimizations and they create more harm than good at the end. Developers or enthusiastic people do not want to deal with such situations. 
* People who use pre-built EFIs don't know how to properly submit an issue about their problems and it becomes a time consuming situation for people who want to help but first have to repeat all basics again and again to make them properly explain their problem.
* actually if two hardwares are really "identical" , there is no problem to use a pre-built EFI yet having a notice like that is to  say " sorry bro , it can't be working for you " It is a common language actually to protect yourself from blaming of others. 
* There are fine guides out there, especially "Dortania" guides are clean and on point but of course they deal with a wider audience and give you only basics to make it work. I created some SSDT files by myself and guides don't give you these informations. you should go search by yourself and come with a conclusion.

These are the first answers came to my mind.
 
As long as you do not discover a new way to implement things, creating your own EFI will change nothing. It will be pretty much same with mine in the end. I already optimized everything I am aware and carefully selected all kexts and necessary drivers. As long as you have the parts I listed, it is good to use my EFI and it creates no problem.

Another example to know what you do is that for example I do not want to reinstall Windows 11 so I don't care about "Secure Boot Enabling". If you want to dual boot macOS and Windows 11, you should find a way to enable Secure Boot by yourself.

When I started hackintoshing again after nearly a decade with this laptop, I came across with a repository by Nihhaar. I used it and it worked but I noticed there were problems. The most important problem I noticed was he used Macbookair7,2 SMBIOS but it should be Macbookpro14 line regarding to specs. I asked him and even though he tried to help, we were not able to find a solution. In order to make USB ports work, we had to set it to Air SMBIOS. Then I asked the question to Rehabman from Tonymacx86. He is a kind of legend for the community. He didn't answer me so many times and just replied "READ" After making so many researches I found that Dell machines use a different type for information passing so it must be set to that way. It is a common knowledge now if you have Dell laptops , you should set CustomSmbiosGuid. 

I hope this post finds you well. You can start a conversation as long as you want but keep that in mind one day I might be long gone and no-one is around so prepare yourself for that day :)
