### ISSUE TITLE
Catalina 10.15.5 update

### ISSUE THREAD

**Issue by DeMikeyyy** [lersy/Dell-7577-Hackintosh-macos-Opencore#7]
Hey bro, how have you been? 

I've been reinstalling macOS today. Thought I might give you an update on my findings 

- The EFI boots macOS Catalina 10.15.5 perfectly with the latest release. 

- Ethernet kext RealtekRTL8111 doesn't work. Had to get the latest version from Goldfish kext repo to get ethernet working.

- The System Serial doesn't stick after saving in ProperTree. The rest does, but if I save after putting the Gen SMBIOS stuff in, SystemSerial reverts back to "GET YOUR OWN" every damn time lol. But I fixed it after I finished my install by first opening config.plist, removing "GET YOUR OWN", safe, open it again and putting the serial number in, that seems to have done the trick. 

- The settings app in Apple ID was stuck for a while trying to log in (probably serial related I guess) so I had to manually stop the settings app. 

- Is it possible to hide the Windows drive in OC? Thing is, if OC accidently boots the Windows drive it's in a automatic repair loop. Also have to activate "AllowSetDefault' so OC always chooses MacOS otherwise it might boot Windows with the ACPI patches and send it in an automatic repair loop.

- If you boot with rEFInd like, you HAVE to disable Bootstrap or else it puts OC first in boot order no matter what.

- Thunderbolt doesn't work so no second screen sadly. The Clover config from wadimw got it working though. He fixed it by spoofing Kaby Lake graphics. Maybe something to look into? I don't want to go back to Clover but it would be nice if I can use a screen. Here's what wadimw said how he fixed it:

"I fixed it for now by spoofing Skylake graphics (I have KabyLake) https://www.tonymacx86.com/threads/readme-common-problems-and-workarounds-on-10-14-mojave.255823/   "

Hope I didn't make this too long, thanks for this, glad I can use this on my laptop

**Comment by lersy** [comment]
hey bro. thanks for asking, I am doing fine. What about you? 

You can use this efi folder for a base and tweak it as you want. We all have different setups than each other. About your findings;

* I think there will be no problem in terms of Catalina anymore. OC is a really nice boot loader and pretty capable of handling nearly all situations. 

* Well I have not used ethernet card for a while now. When I check it, it says version 2.3.0d10 from Mieze repo. Next time, I will try it and upload according to that. 

* I have not used ProperTree so no idea about that. I use plistEdit Pro and recommend it. I know ProperTree has snapshot abilities but because I already added kexts, acpi files, and drivers to config.plist, it is not a big deal to edit one or two lines with it manually. but for the ones who use ProperTree, it is nice to know there is a workaround for it thanks to you. 

* I have no problem about settings app and Apple ID section. All works like a charm so most probably it is because about smbios parameters problem as you said. 

* I do not see any kind of windows or Mac OS drive when I boot into macOS or windows. None of the boot loaders mess with other operating system. I directly boot into Mac OS when I press power button and if I want to play game ( "Rocket League" ,only reason to boot windows for me) I just press F12 and select windows boot manager. You can make these changes to your config.plist to obtain such a behavior with rEFInd. 

>>  Misc >  Boot > ShowPicker is set to "NO"

>> Misc > Security > Scan Policy is 17760515

Since you already disabled Bootstrap these settings should give you what you want when booting to each systems. I like bootstrap personally because otherwise windows boot loader overwrites OC and that is something I do not want. Maybe I will change this scenario as you mentioned in the future. 

*  I do not have a chance to try Thunderbolt because I do not have it. I will dig it a little bit but can't say that it will be ok since I can't try by myself. this is a crazy idea but just replace wadimw properties with your config.plist graphic properties and give it a try. of course do this with caution. try it with usb stick first to see if it works or not. do not replace the config on your hard drive directly while making this kind of changes. play safe. 

it is better to give deeper insides about your setup so I can learn new things and maybe add them into future ones. 

I am sorry for replying late I was in another city and away from pc for a while. have a good day.
